language: go
go:
  - 1.16.x

env:
  global:
    - GO111MODULE=auto

install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0

script:
  - make
  - bin/model

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/count.out
